version: '3.1'
services:
  postgres_hungry_hippogriffs:
    image: postgres:14-alpine
    networks:
      - backend
    restart: always
    container_name: postgres_hungry_hippogriffs
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5454:5432"
#    volumes:
#      - ./postgres:/var/lib/postgresql/data

  app_hungry_hippogriffs:
    image: app_hungry_hippogriffs
    build:
      context: "."
    container_name: app_hungry_hippogriffs
    networks:
      - backend
    ports:
      - 8000:8000
    command: bash -c "poetry run python src/db/session.py"

networks:
  backend:
    driver: bridge
